"""add image to hotel

Revision ID: 22eea0d4fddc
Revises: 98c00138ae61
Create Date: 2024-09-23 13:07:48.732347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22eea0d4fddc'
down_revision: Union[str, None] = '98c00138ae61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('image', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'image')
    # ### end Alembic commands ###
