"""added role to User

Revision ID: 725ef6548f6a
Revises: e83521be6b79
Create Date: 2024-09-04 15:29:35.870761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '725ef6548f6a'
down_revision: Union[str, None] = 'e83521be6b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    role_enum = postgresql.ENUM('CLIENT', 'ADMIN', name='role_enum')
    role_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('CLIENT', 'ADMIN', name='role_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###

    role_enum = postgresql.ENUM('CLIENT', 'ADMIN', name='role_enum')
    role_enum.drop(op.get_bind())
