"""added role to User 2

Revision ID: 7febbd88285c
Revises: 725ef6548f6a
Create Date: 2024-09-04 15:36:19.151738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7febbd88285c'
down_revision: Union[str, None] = '725ef6548f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='role_enum'),
               nullable=False, server_default='CLIENT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='role_enum'),
               nullable=True)
    # ### end Alembic commands ###
