"""remove image_id

Revision ID: b981723b498a
Revises: 22eea0d4fddc
Create Date: 2024-09-24 13:03:47.756964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b981723b498a'
down_revision: Union[str, None] = '22eea0d4fddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
